---
- name: Include distribution-specific variables
  include_vars: "{{ ansible_os_family | regex_replace(' ', '_') | lower }}.yml"

- name: Download installation package
  get_url:
    url: "{{ sentinelone_filename }}"
    dest: "/tmp/{{ sentinelone_filename | basename }}"
    mode: 0644

- name: Include installation tasks
  include_tasks: "install_{{ ansible_os_family | regex_replace(' ', '_') | lower }}.yml"

- name: Set Group/Site token
  command: "/opt/sentinelone/bin/sentinelctl management token set {{ sentinelone_token }}"
  args:
    creates: /opt/sentinelone/.INITIALIZATION_COMPLETE
  become: true
  notify: Create initialization file
  when: sentinelone_token is defined and sentinelone_token != ''

- name: Start agent
  command: /opt/sentinelone/bin/sentinelctl control start
  become: true
