---
- name: Create initialization file
  file:
    path: /opt/sentinelone/.INITIALIZATION_COMPLETE
    owner: root
    group: root
    mode: '0644'
    state: touch
  become: true
  when: token_set.changed
