---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Set SentinelONE client installation file (Debian)
      ansible.builtin.set_fact:
        file_sentinelone: sentinelone_latest.deb
      when: ansible_os_family == 'Debian'

    - name: Set SentinelONE client installation file (Red Hat)
      ansible.builtin.set_fact:
        file_sentinelone: sentinelone_latest.rpm
      when: ansible_os_family == 'RedHat'

  roles:
    - role: stdevel.sentinelone_client
      sentinelone_filename: "{{ file_sentinelone }}"
      # sentinelone_token: '...'
      # sentinelone_gpgkey: '...'
